Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          NeosRulez.React.CookieOptIn:
            - 'Component/*'
            - 'NodeTypes/*'
      defaultLanguage: 'de'
    fusion:
      autoInclude:
        NeosRulez.React.CookieOptIn: true